### ISSUE TITLE
New user needs help

### ISSUE THREAD

**Issue by ghost** [kalliope-project/kalliope_neuron_hue#3]
Just started using Kalliope and trying to get this skill working, haven't tried any other skills but I can't seem to get it running, I installed it, paired it with my hue hub, in the brain.yml file I added a 'hue.yml' to the includes list and created a file, I copy-pasted this 
` - name: "switch-on-bedroom"
   signals:
     - order: "turn the light on in the bedroom"
   neurons:
     - hue:
        bridge_ip: "192.168.0.7"
        groups_name:
         - "hall"
         - "living-room"
        state: "on"`

 into the file and changed the IP to my hue bridge but whenever I run kalliope I get an error "expected <block end>, but found '<block sequence start>'" for the 'name:' line.. Amd I suppose to be doing something else or what exactly do I put into the hue.yml file to get it to work?

**Comment by Sispheor** [comment]
Please use syntax highlight. It's difficult to find the indentation error here without formating

**Comment by ghost** [comment]
> 
> 
> Please use syntax highlight. It's difficult to find the indentation error here without formating

Idk how to even format syntax on here, lol sorry I don't use github much, but here's a screenshot of my file. 

![Capture](https://user-images.githubusercontent.com/61924853/104131879-a5353880-5336-11eb-8232-2e6ed7e44ff1.PNG)

**Comment by Sispheor** [comment]
Your syntax is wrong.
Signal and neurons flags need to be aligned with name.
